import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/mobileHeader";
import Image from "next/image";
import React, { useEffect } from "react";

import Link from "next/link";
import { motion, useInView } from "framer-motion";
import MenuButton from "@/components/MenuButton";
import Button from "@/components/Button";
import MobileHeader from "@/components/mobileHeader";
import DesktopHeader from "@/components/desktopHeader";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="max-w-[1600px] mx-auto">
        {/* <Header /> */}
        <nav className="flex p-4 justify-between  items-center font-sans">
          <Link className="cursor-pointer" href="/">
            <div className="flex gap-2 items-center">
              <Image
                className="object-contain"
                src="/images/logo.png"
                width={56}
                height={55}
                alt="logo"
              />
              <p className="text-[#474747] font-playfair text-[35px] gap-4 italic font-[500]">
                Chef Deejah
              </p>
            </div>
          </Link>
          <DesktopHeader />
          <MobileHeader />
          <Button className="hidden md:block">Book a table</Button>
        </nav>
        <div>{children}</div>
      </body>
    </html>
  );
}
